# Generated by Django 5.1.7 on 2025-07-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stylesonlayer",
            name="popup",
            field=models.TextField(blank=True, null=True),
        ),
    ]
