# Generated by Django 5.1.7 on 2025-03-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmapdata',
            name='feature_url_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmapdata',
            name='geojson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmapdata',
            name='icon_url_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmapdata',
            name='image_url_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmapdata',
            name='ogm_map_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='feature_url_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='geojson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='icon_url_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='image_url_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='ogm_map_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
