# Generated by Django 5.1.7 on 2025-07-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0002_stylesonlayer_popup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallayer",
            name="description",
            field=models.TextField(
                help_text="The layer description that will appear in the map legend to help people understand what the layer data represents."
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="description",
            field=models.TextField(
                help_text="The layer description that will appear in the map legend to help people understand what the layer data represents."
            ),
        ),
    ]
