# Generated by Django 5.1.7 on 2025-03-16 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0002_historicalquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalquestion',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='body',
            new_name='content',
        ),
    ]
