# Generated by Django 5.1.7 on 2025-03-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0002_alter_historicalmapdata_feature_url_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmapdata',
            name='name',
            field=models.CharField(default='Waterfall Data', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapdata',
            name='name',
            field=models.CharField(default='Waterfall Data', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalmapdata',
            name='feature_url_template',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmapdata',
            name='icon_url_template',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmapdata',
            name='image_url_template',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='feature_url_template',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='icon_url_template',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='image_url_template',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
