# Generated by Django 5.1.7 on 2025-07-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0003_alter_historicallayer_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstyle",
            name="marker_icon",
            field=models.TextField(
                blank=True,
                help_text="The image that will appear at each point this style is applied to. Accepts PNG, JPEG, and SVG files.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="marker_icon",
            field=models.FileField(
                blank=True,
                help_text="The image that will appear at each point this style is applied to. Accepts PNG, JPEG, and SVG files.",
                null=True,
                upload_to="marker_icons/",
            ),
        ),
    ]
