# Generated by Django 5.1.7 on 2025-03-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0003_historicalmapdata_name_mapdata_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmapdata',
            name='ogm_map_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='ogm_map_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
