# Generated by Django 5.1.7 on 2025-03-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0004_alter_historicalmapdata_ogm_map_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubquestion',
            name='button_text',
            field=models.CharField(default='Make your move', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subquestion',
            name='button_text',
            field=models.CharField(default='Make your Move', max_length=255),
            preserve_default=False,
        ),
    ]
