# Generated by Django 5.1.7 on 2025-07-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0004_alter_historicalstyle_marker_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallayer",
            name="serialized_leaflet_json",
            field=models.JSONField(blank=True, default="{}"),
        ),
        migrations.AddField(
            model_name="layer",
            name="serialized_leaflet_json",
            field=models.JSONField(blank=True, default="{}"),
        ),
    ]
