# Generated by Django 5.1.7 on 2025-03-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0005_historicalsubquestion_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
