# Generated by Django 5.1.7 on 2025-07-18 22:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0006_alter_historicallayer_serialized_leaflet_json_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayerGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("group_name", models.CharField(max_length=255)),
                (
                    "group_description",
                    models.TextField(blank=True, help_text="Optional description."),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="historicallayer",
            name="serialized_leaflet_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="layer",
            name="serialized_leaflet_json",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="LayerOnQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_by_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the layer is active by default when a new question is loaded.",
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rush.layer"
                    ),
                ),
                (
                    "layer_group",
                    models.ForeignKey(
                        help_text="The title of the layer group.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rush.layergroup",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rush.question"
                    ),
                ),
            ],
        ),
    ]
