# Generated by Django 5.1.7 on 2025-03-17 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0006_historicalquestion_image_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initiative',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='initiative_images/'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='initiative',
            field=models.ManyToManyField(to='rush.initiative'),
        ),
        migrations.CreateModel(
            name='InitiativeTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('initiative', models.ManyToManyField(to='rush.initiative')),
            ],
        ),
    ]
