# Generated by Django 5.1.7 on 2025-07-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0007_layergroup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="initiatives",
            field=models.ManyToManyField(blank=True, to="rush.initiative"),
        ),
    ]
