# Generated by Django 5.1.7 on 2025-03-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0007_initiative_content_initiative_image_initiative_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='initiative',
            new_name='initiatives',
        ),
    ]
