# Generated by Django 5.1.7 on 2025-07-18 23:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0008_alter_question_initiatives"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "url_route",
                    models.CharField(
                        help_text="The url route to use when navigating to this page.",
                        max_length=255,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the webpage.", max_length=255
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The content that will appear on the webpage."
                    ),
                ),
            ],
        ),
    ]
