# Generated by Django 5.1.7 on 2025-03-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0008_rename_initiative_question_initiatives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiativetag',
            name='initiative',
        ),
        migrations.AddField(
            model_name='initiativetag',
            name='initiatives',
            field=models.ManyToManyField(related_name='tags', to='rush.initiative'),
        ),
    ]
