# Generated by Django 5.1.7 on 2025-03-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0009_remove_initiativetag_initiative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiativetag',
            name='initiatives',
        ),
        migrations.AddField(
            model_name='initiative',
            name='tags',
            field=models.ManyToManyField(related_name='initiatives', to='rush.initiativetag'),
        ),
    ]
