# Generated by Django 5.1.7 on 2025-07-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0009_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="url_route",
        ),
    ]
