# Generated by Django 5.1.7 on 2025-03-19 21:17

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0010_remove_initiativetag_initiatives_initiative_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryMapData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lifespan', models.DurationField(default=datetime.timedelta(seconds=300))),
                ('map_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rush.mapdata')),
            ],
        ),
    ]
