# Generated by Django 5.1.7 on 2025-07-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0007_alter_historicallayer_serialized_leaflet_json_and_more'),
        ('rush', '0010_remove_page_url_route'),
    ]

    operations = [
    ]
