# Generated by Django 5.1.7 on 2025-08-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0010_remove_page_url_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalquestiontab",
            name="subtitle",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questiontab",
            name="subtitle",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
