# Generated by Django 5.1.7 on 2025-03-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0011_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='point',
        ),
        migrations.AddField(
            model_name='location',
            name='geojson',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
