# Generated by Django 5.1.7 on 2025-08-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0011_historicalquestiontab_subtitle_questiontab_subtitle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalquestiontab",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="questiontab",
            name="subtitle",
        ),
        migrations.AddField(
            model_name="historicalquestion",
            name="subtitle",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="subtitle",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
