# Generated by Django 5.1.7 on 2025-08-13 23:25 -- Edited by Sam Morris.

from django.db import migrations

from rush.migration_helpers import big_int_to_uuid_operations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0012_remove_historicalquestiontab_subtitle_and_more"),
    ]

    operations = [
        *big_int_to_uuid_operations("layeronquestion", "id"),
    ]
