# Generated by Django 5.1.7 on 2025-03-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0012_remove_location_point_location_geojson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
