# Generated by Django 5.1.7 on 2025-08-13 23:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0012_remove_historicalquestiontab_subtitle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layeronquestion",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
