# Generated by Django 5.1.7 on 2025-03-23 03:16

import django.db.models.deletion
import rush.models.map.style
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0013_delete_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PathOptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('stroke', models.BooleanField()),
                ('color', models.CharField(max_length=32)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opacity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('lineCap', models.CharField(choices=[('butt', 'Butt'), ('round', 'Round'), ('square', 'Square')], max_length=32)),
                ('lineJoin', models.CharField(choices=[('arcs', 'Arcs'), ('bevel', 'Bevel'), ('miter', 'Miter'), ('miter-clip', 'Miter Clip'), ('round', 'Round')], max_length=32)),
                ('dashArray', models.CharField(help_text="Only digits and whitespace allowed (e.g., '12 34 56')", max_length=32, validators=[rush.models.map.style.validate_only_integers_and_whitespace])),
                ('dashOffset', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPathOptions',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.CharField(max_length=255)),
                ('stroke', models.BooleanField()),
                ('color', models.CharField(max_length=32)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opacity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('lineCap', models.CharField(choices=[('butt', 'Butt'), ('round', 'Round'), ('square', 'Square')], max_length=32)),
                ('lineJoin', models.CharField(choices=[('arcs', 'Arcs'), ('bevel', 'Bevel'), ('miter', 'Miter'), ('miter-clip', 'Miter Clip'), ('round', 'Round')], max_length=32)),
                ('dashArray', models.CharField(help_text="Only digits and whitespace allowed (e.g., '12 34 56')", max_length=32, validators=[rush.models.map.style.validate_only_integers_and_whitespace])),
                ('dashOffset', models.CharField(max_length=32)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical path options',
                'verbose_name_plural': 'historical path optionss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
