# Generated by Django 5.1.7 on 2025-08-13 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0013_alter_layeronquestion_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questiontab",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tabs",
                to="rush.question",
            ),
        ),
    ]
