# Generated by Django 5.1.7 on 2025-09-12 00:32

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0014_alter_questiontab_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layeronquestion",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
