# Generated by Django 5.1.7 on 2025-03-23 03:24

import rush.models.map.style
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0014_pathoptions_historicalpathoptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmapdata',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical map data', 'verbose_name_plural': 'historical Map Data'},
        ),
        migrations.AlterModelOptions(
            name='historicalpathoptions',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical path options', 'verbose_name_plural': 'historical Path Options'},
        ),
        migrations.AlterModelOptions(
            name='mapdata',
            options={'verbose_name_plural': 'Map Data'},
        ),
        migrations.AlterModelOptions(
            name='pathoptions',
            options={'verbose_name_plural': 'Path Options'},
        ),
        migrations.AlterField(
            model_name='historicalpathoptions',
            name='dashArray',
            field=models.CharField(blank=True, help_text="Only digits and whitespace allowed (e.g., '12 34 56')", max_length=32, null=True, validators=[rush.models.map.style.validate_only_integers_and_whitespace]),
        ),
        migrations.AlterField(
            model_name='historicalpathoptions',
            name='dashOffset',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpathoptions',
            name='opacity',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='historicalpathoptions',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pathoptions',
            name='dashArray',
            field=models.CharField(blank=True, help_text="Only digits and whitespace allowed (e.g., '12 34 56')", max_length=32, null=True, validators=[rush.models.map.style.validate_only_integers_and_whitespace]),
        ),
        migrations.AlterField(
            model_name='pathoptions',
            name='dashOffset',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='pathoptions',
            name='opacity',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pathoptions',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
