# Generated by Django 5.1.7 on 2025-03-23 03:28

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0015_alter_historicalmapdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpathoptions',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='pathoptions',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
