# Generated by Django 5.1.7 on 2025-09-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0011_merge_20250722_2020'),
        ('rush', '0015_alter_layeronquestion_id'),
    ]

    operations = [
    ]
