# Generated by Django 5.1.7 on 2025-03-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0016_alter_historicalpathoptions_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpathoptions',
            old_name='color',
            new_name='stroke_color',
        ),
        migrations.RenameField(
            model_name='historicalpathoptions',
            old_name='dashArray',
            new_name='stroke_dash_array',
        ),
        migrations.RenameField(
            model_name='historicalpathoptions',
            old_name='dashOffset',
            new_name='stroke_dash_offset',
        ),
        migrations.RenameField(
            model_name='historicalpathoptions',
            old_name='opacity',
            new_name='stroke_opacity',
        ),
        migrations.RenameField(
            model_name='historicalpathoptions',
            old_name='weight',
            new_name='stroke_weight',
        ),
        migrations.RenameField(
            model_name='pathoptions',
            old_name='color',
            new_name='stroke_color',
        ),
        migrations.RenameField(
            model_name='pathoptions',
            old_name='dashArray',
            new_name='stroke_dash_array',
        ),
        migrations.RenameField(
            model_name='pathoptions',
            old_name='dashOffset',
            new_name='stroke_dash_offset',
        ),
        migrations.RenameField(
            model_name='pathoptions',
            old_name='opacity',
            new_name='stroke_opacity',
        ),
        migrations.RenameField(
            model_name='pathoptions',
            old_name='weight',
            new_name='stroke_weight',
        ),
        migrations.RemoveField(
            model_name='historicalpathoptions',
            name='lineCap',
        ),
        migrations.RemoveField(
            model_name='historicalpathoptions',
            name='lineJoin',
        ),
        migrations.RemoveField(
            model_name='historicalpathoptions',
            name='stroke',
        ),
        migrations.RemoveField(
            model_name='pathoptions',
            name='lineCap',
        ),
        migrations.RemoveField(
            model_name='pathoptions',
            name='lineJoin',
        ),
        migrations.RemoveField(
            model_name='pathoptions',
            name='stroke',
        ),
        migrations.AddField(
            model_name='historicalpathoptions',
            name='draw_stroke',
            field=models.BooleanField(default=True, help_text="True when you want to draw the line. Setting this to 'False', for example, will remove the borders from a polygon."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpathoptions',
            name='stroke_line_cap',
            field=models.CharField(choices=[('butt', 'Butt'), ('round', 'Round'), ('square', 'Square')], default='round', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalpathoptions',
            name='stroke_line_join',
            field=models.CharField(choices=[('arcs', 'Arcs'), ('bevel', 'Bevel'), ('miter', 'Miter'), ('miter-clip', 'Miter Clip'), ('round', 'Round')], default='round', max_length=32),
        ),
        migrations.AddField(
            model_name='pathoptions',
            name='draw_stroke',
            field=models.BooleanField(default=True, help_text="True when you want to draw the line. Setting this to 'False', for example, will remove the borders from a polygon."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pathoptions',
            name='stroke_line_cap',
            field=models.CharField(choices=[('butt', 'Butt'), ('round', 'Round'), ('square', 'Square')], default='round', max_length=32),
        ),
        migrations.AddField(
            model_name='pathoptions',
            name='stroke_line_join',
            field=models.CharField(choices=[('arcs', 'Arcs'), ('bevel', 'Bevel'), ('miter', 'Miter'), ('miter-clip', 'Miter Clip'), ('round', 'Round')], default='round', max_length=32),
        ),
    ]
