# Generated by Django 5.1.7 on 2025-09-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0016_merge_20250912_1941"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="background_image",
            field=models.ImageField(
                blank=True,
                help_text="An optional background image that will appear behind the main content of the page.",
                null=True,
                upload_to="page_background_images/",
            ),
        ),
    ]
