# Generated by Django 5.1.7 on 2025-03-24 03:33

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0017_rename_color_historicalpathoptions_stroke_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpathoptions',
            name='draw_fill',
            field=models.BooleanField(default=True, help_text='Check this box if you want to fill a polygon.'),
        ),
        migrations.AddField(
            model_name='historicalpathoptions',
            name='fill_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='historicalpathoptions',
            name='fill_opacity',
            field=models.DecimalField(blank=True, decimal_places=3, default=1.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalpathoptions',
            name='fill_rule',
            field=models.CharField(blank=True, choices=[('nonzero', 'Nonzero'), ('evenodd', 'Evenodd')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='historicalpathoptions',
            name='fill_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pathoptions',
            name='draw_fill',
            field=models.BooleanField(default=True, help_text='Check this box if you want to fill a polygon.'),
        ),
        migrations.AddField(
            model_name='pathoptions',
            name='fill_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='pathoptions',
            name='fill_opacity',
            field=models.DecimalField(blank=True, decimal_places=3, default=1.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pathoptions',
            name='fill_rule',
            field=models.CharField(blank=True, choices=[('nonzero', 'Nonzero'), ('evenodd', 'Evenodd')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='pathoptions',
            name='fill_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpathoptions',
            name='draw_stroke',
            field=models.BooleanField(help_text='Check this box when you want to draw the line. Unchecking this box, for example, will remove the borders from a polygon.'),
        ),
        migrations.AlterField(
            model_name='pathoptions',
            name='draw_stroke',
            field=models.BooleanField(help_text='Check this box when you want to draw the line. Unchecking this box, for example, will remove the borders from a polygon.'),
        ),
    ]
