# Generated by Django 5.1.7 on 2025-09-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0017_page_background_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmapdata",
            name="provider",
            field=models.CharField(
                choices=[("geojson", "Geojson"), ("open_green_map", "Open Green Map")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="mapdata",
            name="provider",
            field=models.CharField(
                choices=[("geojson", "Geojson"), ("open_green_map", "Open Green Map")],
                max_length=255,
            ),
        ),
    ]
