# Generated by Django 5.1.7 on 2025-03-24 03:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0018_historicalpathoptions_draw_fill_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPathOptions',
            new_name='HistoricalStyle',
        ),
        migrations.RenameModel(
            old_name='PathOptions',
            new_name='Style',
        ),
        migrations.AlterModelOptions(
            name='historicalstyle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical style', 'verbose_name_plural': 'historical Path Options'},
        ),
    ]
