# Generated by Django 5.1.7 on 2025-09-15 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0018_alter_historicalmapdata_provider_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenGreenMapProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("map_link", models.CharField(max_length=2000)),
                (
                    "campagn_link",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="historicalmapdata",
            name="feature_url_template",
        ),
        migrations.RemoveField(
            model_name="historicalmapdata",
            name="icon_url_template",
        ),
        migrations.RemoveField(
            model_name="historicalmapdata",
            name="image_url_template",
        ),
        migrations.RemoveField(
            model_name="historicalmapdata",
            name="ogm_map_id",
        ),
        migrations.RemoveField(
            model_name="mapdata",
            name="feature_url_template",
        ),
        migrations.RemoveField(
            model_name="mapdata",
            name="icon_url_template",
        ),
        migrations.RemoveField(
            model_name="mapdata",
            name="image_url_template",
        ),
        migrations.RemoveField(
            model_name="mapdata",
            name="ogm_map_id",
        ),
        migrations.AddField(
            model_name="historicalmapdata",
            name="opengreenmap",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="rush.opengreenmapprovider",
            ),
        ),
        migrations.AddField(
            model_name="mapdata",
            name="opengreenmap",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rush.opengreenmapprovider",
            ),
        ),
    ]
