# Generated by Django 5.1.7 on 2025-09-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0019_opengreenmapprovider_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalmapdata",
            old_name="opengreenmap",
            new_name="ogm_provider",
        ),
        migrations.RenameField(
            model_name="mapdata",
            old_name="opengreenmap",
            new_name="ogm_provider",
        ),
    ]
