# Generated by Django 5.1.7 on 2025-03-27 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0019_rename_historicalpathoptions_historicalstyle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalstyle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical style', 'verbose_name_plural': 'historical styles'},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={},
        ),
    ]
