# Generated by Django 5.1.7 on 2025-04-10 23:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0020_alter_historicalstyle_options_alter_style_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
            ],
        ),
    ]
