# Generated by Django 5.1.7 on 2025-09-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0020_rename_opengreenmap_historicalmapdata_ogm_provider_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="opengreenmapprovider",
            old_name="campagn_link",
            new_name="campaign_link",
        ),
    ]
