# Generated by Django 5.1.7 on 2025-09-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0021_rename_campagn_link_opengreenmapprovider_campaign_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmapdata",
            name="geojson",
            field=models.JSONField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="mapdata",
            name="geojson",
            field=models.JSONField(blank=True, default="", null=True),
        ),
    ]
