# Generated by Django 5.1.7 on 2025-05-03 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0021_deploylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploylog',
            name='filename',
        ),
        migrations.AddField(
            model_name='deploylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deploylog',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('failed', 'Failed'), ('succeeded', 'Succeeded')], default='failed', max_length=255),
            preserve_default=False,
        ),
    ]
