# Generated by Django 5.1.7 on 2025-05-04 20:10

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0022_remove_deploylog_filename_deploylog_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('button_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='subquestion',
            name='sub_question',
        ),
        migrations.RemoveField(
            model_name='historicalquestion',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subtitle',
        ),
        migrations.CreateModel(
            name='HistoricalQuestionTab',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('button_text', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical question tab',
                'verbose_name_plural': 'historical question tabs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='sub_question',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rush.questiontab'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rush.questiontab'),
        ),
        migrations.DeleteModel(
            name='HistoricalSubQuestion',
        ),
        migrations.DeleteModel(
            name='SubQuestion',
        ),
    ]
