# Generated by Django 5.1.7 on 2025-09-16 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0022_alter_historicalmapdata_geojson_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoJsonProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("geojson", models.JSONField(default="")),
            ],
        ),
    ]
