# Generated by Django 5.1.7 on 2025-05-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0023_questiontab_remove_subquestion_sub_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquestion',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='layer',
        ),
        migrations.AddField(
            model_name='question',
            name='layer',
            field=models.ManyToManyField(to='rush.layer'),
        ),
    ]
