# Generated by Django 5.1.7 on 2025-05-04 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0024_remove_historicalquestion_layer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='layer',
        ),
        migrations.AddField(
            model_name='historicallayer',
            name='questions',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rush.question'),
        ),
        migrations.AddField(
            model_name='layer',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='layers', to='rush.question'),
        ),
    ]
