# Generated by Django 5.1.7 on 2025-05-04 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0025_remove_question_layer_historicallayer_questions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallayer',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='layer',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='historicallayer',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='questions',
        ),
    ]
