# Generated by Django 5.1.7 on 2025-09-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0025_remove_mapdata_geojson_provider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmapdata",
            name="_geojson",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="mapdata",
            name="_geojson",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
