# Generated by Django 5.1.7 on 2025-09-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0026_alter_historicalmapdata__geojson_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stylesonlayer",
            name="legend_description",
            field=models.CharField(
                default="E.g., 'Grassland', '0-25%', or '>3 Tree Protection Score'.",
                help_text="A short description of what this style represents on the map.",
                max_length=255,
            ),
        ),
    ]
