# Generated by Django 5.1.7 on 2025-05-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0026_rename_title_historicallayer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='rush.layer'),
        ),
    ]
