# Generated by Django 5.1.7 on 2025-05-04 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0027_question_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquestion',
            name='sub_question',
        ),
        migrations.RemoveField(
            model_name='historicalquestiontab',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sub_question',
        ),
        migrations.RemoveField(
            model_name='questiontab',
            name='button_text',
        ),
        migrations.AddField(
            model_name='historicalquestiontab',
            name='question',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rush.question'),
        ),
        migrations.AddField(
            model_name='questiontab',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='rush.question'),
        ),
    ]
