# Generated by Django 5.1.7 on 2025-09-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0028_stylesonlayer_legend_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stylesonlayer",
            name="legend_order",
            field=models.IntegerField(
                default=0,
                help_text="Optional ordering for the styles to be put in the legend. If you want this style to be at the top of the legend, compared to other styles on this layer, use a lower number. Without setting this field there is no guarantee of the order of these styles in the legend!",
            ),
        ),
    ]
