# Generated by Django 5.1.7 on 2025-05-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0028_remove_historicalquestion_sub_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquestion',
            name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
    ]
