# Generated by Django 5.1.7 on 2025-09-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0029_alter_stylesonlayer_legend_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeployLog",
        ),
    ]
