# Generated by Django 5.1.7 on 2025-05-04 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0029_remove_historicalquestion_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GPTQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GPTQuestionLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rush.gptlayer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rush.gptquestion')),
            ],
            options={
                'unique_together': {('question', 'layer')},
            },
        ),
        migrations.AddField(
            model_name='gptquestion',
            name='layers',
            field=models.ManyToManyField(related_name='gpt_questions', through='rush.GPTQuestionLayer', to='rush.gptlayer'),
        ),
    ]
