# Generated by Django 5.1.7 on 2025-10-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0030_delete_deploylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
