# Generated by Django 5.1.7 on 2025-05-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0030_gptlayer_gptquestion_gptquestionlayer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptquestion',
            name='layers',
        ),
        migrations.AlterField(
            model_name='gptlayer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gptquestion',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='GPTQuestionLayer',
        ),
    ]
