# Generated by Django 5.1.7 on 2025-10-01 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0030_delete_deploylog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="layer",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="style",
            options={"base_manager_name": "objects"},
        ),
    ]
