# Generated by Django 5.1.7 on 2025-10-09 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0030_delete_deploylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="link",
            field=models.CharField(
                default="fake-test-url",
                max_length=2048,
                validators=[django.core.validators.URLValidator()],
            ),
            preserve_default=False,
        ),
    ]
