# Generated by Django 5.1.7 on 2025-05-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0031_remove_gptquestion_layers_alter_gptlayer_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GPTLayer',
        ),
        migrations.DeleteModel(
            name='GPTQuestion',
        ),
    ]
