# Generated by Django 5.1.7 on 2025-05-05 20:44

import colorfield.fields
import django.db.models.deletion
import rush.models.map
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0032_delete_gptlayer_delete_gptquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstyle',
            name='fill_weight',
        ),
        migrations.RemoveField(
            model_name='style',
            name='fill_weight',
        ),
        migrations.AlterField(
            model_name='historicalstyle',
            name='draw_fill',
            field=models.BooleanField(default=True, help_text='Check this box if you want to fill the polygon.'),
        ),
        migrations.AlterField(
            model_name='historicalstyle',
            name='stroke_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='historicalstyle',
            name='stroke_dash_array',
            field=models.CharField(blank=True, help_text="The pattern of dashes and gaps for the outline, e.g., '5 5' for 5 pixel long lines separated by 5 pixels of whiespace. Only digits and whitespace are allowed (e.g., '12 34 56')", max_length=32, null=True, validators=[rush.models.map.validate_only_integers_and_whitespace]),
        ),
        migrations.AlterField(
            model_name='historicalstyle',
            name='stroke_dash_offset',
            field=models.CharField(blank=True, help_text='Offset where the dash pattern starts along the outline path.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstyle',
            name='stroke_line_cap',
            field=models.CharField(choices=[('butt', 'Butt'), ('round', 'Round'), ('square', 'Square')], default='round', help_text='The shape of the end of a stroke. Options: butt, round, or square.', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalstyle',
            name='stroke_line_join',
            field=models.CharField(choices=[('arcs', 'Arcs'), ('bevel', 'Bevel'), ('miter', 'Miter'), ('miter-clip', 'Miter Clip'), ('round', 'Round')], default='round', help_text='The shape used to join two lines. Options: miter, round, or bevel.', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalstyle',
            name='stroke_opacity',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=5, verbose_name='Transparency'),
        ),
        migrations.AlterField(
            model_name='historicalstyle',
            name='stroke_weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Thickness'),
        ),
        migrations.AlterField(
            model_name='style',
            name='draw_fill',
            field=models.BooleanField(default=True, help_text='Check this box if you want to fill the polygon.'),
        ),
        migrations.AlterField(
            model_name='style',
            name='stroke_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='style',
            name='stroke_dash_array',
            field=models.CharField(blank=True, help_text="The pattern of dashes and gaps for the outline, e.g., '5 5' for 5 pixel long lines separated by 5 pixels of whiespace. Only digits and whitespace are allowed (e.g., '12 34 56')", max_length=32, null=True, validators=[rush.models.map.validate_only_integers_and_whitespace]),
        ),
        migrations.AlterField(
            model_name='style',
            name='stroke_dash_offset',
            field=models.CharField(blank=True, help_text='Offset where the dash pattern starts along the outline path.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='stroke_line_cap',
            field=models.CharField(choices=[('butt', 'Butt'), ('round', 'Round'), ('square', 'Square')], default='round', help_text='The shape of the end of a stroke. Options: butt, round, or square.', max_length=32),
        ),
        migrations.AlterField(
            model_name='style',
            name='stroke_line_join',
            field=models.CharField(choices=[('arcs', 'Arcs'), ('bevel', 'Bevel'), ('miter', 'Miter'), ('miter-clip', 'Miter Clip'), ('round', 'Round')], default='round', help_text='The shape used to join two lines. Options: miter, round, or bevel.', max_length=32),
        ),
        migrations.AlterField(
            model_name='style',
            name='stroke_opacity',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=5, verbose_name='Transparency'),
        ),
        migrations.AlterField(
            model_name='style',
            name='stroke_weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Thickness'),
        ),
        migrations.CreateModel(
            name='StylesOnLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rush.layer')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rush.style')),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='styles',
            field=models.ManyToManyField(through='rush.StylesOnLayer', to='rush.style'),
        ),
    ]
