# Generated by Django 5.1.7 on 2025-10-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0032_populate_question_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalquestion",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
