# Generated by Django 5.1.7 on 2025-10-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0031_initiative_link"),
        ("rush", "0033_alter_historicalquestion_slug_alter_question_slug"),
    ]

    operations = []
