# Generated by Django 5.1.7 on 2025-05-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0033_remove_historicalstyle_fill_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstyle',
            name='marker_icon',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstyle',
            name='marker_icon_opacity',
            field=models.DecimalField(blank=True, decimal_places=3, default=1.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='marker_icon',
            field=models.ImageField(blank=True, null=True, upload_to='marker_icons/'),
        ),
        migrations.AddField(
            model_name='style',
            name='marker_icon_opacity',
            field=models.DecimalField(blank=True, decimal_places=3, default=1.0, max_digits=5, null=True),
        ),
    ]
