# Generated by Django 5.1.7 on 2025-05-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0034_historicalstyle_marker_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstyle',
            name='draw_marker',
            field=models.BooleanField(default=True, help_text='Check this box if you want to draw the marker icon on each point this style is applied to.'),
        ),
        migrations.AddField(
            model_name='style',
            name='draw_marker',
            field=models.BooleanField(default=True, help_text='Check this box if you want to draw the marker icon on each point this style is applied to.'),
        ),
        migrations.AlterField(
            model_name='historicalstyle',
            name='marker_icon',
            field=models.TextField(blank=True, help_text='The image that will appear at each point this style is applied to.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='marker_icon',
            field=models.ImageField(blank=True, help_text='The image that will appear at each point this style is applied to.', null=True, upload_to='marker_icons/'),
        ),
    ]
