# Generated by Django 5.1.7 on 2025-06-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0035_historicalstyle_draw_marker_style_draw_marker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstyle',
            name='stroke_line_join',
            field=models.CharField(choices=[('arcs', 'Arcs'), ('bevel', 'Bevel'), ('miter', 'Miter'), ('miter-clip', 'Miter Clip'), ('round', 'Round')], default='round', help_text='The shape used to join two lines. Options: arcs, bevel, miter, miter clip, or round.', max_length=32),
        ),
        migrations.AlterField(
            model_name='style',
            name='stroke_line_join',
            field=models.CharField(choices=[('arcs', 'Arcs'), ('bevel', 'Bevel'), ('miter', 'Miter'), ('miter-clip', 'Miter Clip'), ('round', 'Round')], default='round', help_text='The shape used to join two lines. Options: arcs, bevel, miter, miter clip, or round.', max_length=32),
        ),
    ]
