# Generated by Django 5.2.7 on 2025-10-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0035_migrate_domain_url_in_serialized_leaflet_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmapdata",
            name="provider_state",
            field=models.CharField(
                choices=[
                    ("unset", "Unset"),
                    ("geojson", "Geojson"),
                    ("geotiff", "Geotiff"),
                    ("open_green_map", "Open Green Map"),
                ],
                default="unset",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="mapdata",
            name="provider_state",
            field=models.CharField(
                choices=[
                    ("unset", "Unset"),
                    ("geojson", "Geojson"),
                    ("geotiff", "Geotiff"),
                    ("open_green_map", "Open Green Map"),
                ],
                default="unset",
                max_length=255,
            ),
        ),
    ]
