# Generated by Django 5.1.7 on 2025-06-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0036_alter_historicalstyle_stroke_line_join_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylesonlayer',
            name='value',
            field=models.TextField(default='true'),
        ),
    ]
