# Generated by Django 5.2.7 on 2025-10-15 15:58

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0036_alter_historicalmapdata_provider_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmapdata",
            name="geotiff",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mapdata",
            name="geotiff",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(
                    access_key="005fc44d4c8f7110000000001",
                    bucket_name="rush-webmap-raster",
                    secret_key="K005Va9xk3hPkN0qndyWuDbfRYKM2VQ",
                ),
                upload_to="",
            ),
        ),
    ]
