# Generated by Django 5.2.7 on 2025-10-15 16:49

import rush.models.validators
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0037_historicalmapdata_geotiff_mapdata_geotiff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmapdata",
            name="geotiff",
            field=models.TextField(
                blank=True,
                help_text="A GeoTIFF file to upload. It may take up to a couple minutes to upload depending on the file size.",
                max_length=100,
                null=True,
                validators=[rush.models.validators.validate_tiff],
            ),
        ),
        migrations.AlterField(
            model_name="mapdata",
            name="geotiff",
            field=models.FileField(
                blank=True,
                help_text="A GeoTIFF file to upload. It may take up to a couple minutes to upload depending on the file size.",
                null=True,
                storage=storages.backends.s3.S3Storage(
                    access_key="005fc44d4c8f7110000000001",
                    bucket_name="rush-webmap-raster",
                    default_acl="public-read",
                    endpoint_url="https://s3.us-east-005.backblazeb2.com",
                    region_name="us-east-005",
                    secret_key="K005Va9xk3hPkN0qndyWuDbfRYKM2VQ",
                ),
                upload_to="",
                validators=[rush.models.validators.validate_tiff],
            ),
        ),
    ]
