# Generated by Django 5.1.7 on 2025-06-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0037_stylesonlayer_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylesonlayer',
            old_name='value',
            new_name='feature_mapping',
        ),
    ]
