# Generated by Django 5.1.7 on 2025-06-10 15:20

import uuid

from django.db import migrations, models

"""
For replacing a model that has already been created with the Django primary key default (BigInt)
with a model that uses UUID instead. In this case, the StylesOnLayer model was accidentally created
with a BigInt instead of a UUID.
"""


def generate_uuids(apps, schema_editor):
    StylesOnLayer = apps.get_model("rush", "StylesOnLayer")
    for obj in StylesOnLayer.objects.all():
        obj.new_uuid = uuid.uuid4()
        obj.save(update_fields=["new_uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0038_rename_value_stylesonlayer_feature_mapping"),
    ]

    operations = [
        # Step 1: Add a new UUID field
        migrations.AddField(
            model_name="stylesonlayer",
            name="new_uuid",
            field=models.UUIDField(null=True, default=None),
        ),
        # Step 2: Populate new_uuid with new UUIDs
        migrations.RunPython(generate_uuids, reverse_code=migrations.RunPython.noop),
        # Step 3: Remove the old id field
        migrations.RemoveField(
            model_name="stylesonlayer",
            name="id",
        ),
        # Step 4: Rename new_uuid to id and make it primary key
        migrations.RenameField(
            model_name="stylesonlayer",
            old_name="new_uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="stylesonlayer",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
