# Generated by Django 5.2.7 on 2025-10-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0038_alter_historicalmapdata_geotiff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallayer",
            name="serialized_leaflet_json",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="layer",
            name="serialized_leaflet_json",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
