# Generated by Django 5.1.7 on 2025-06-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0039_alter_stylesonlayer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmapdata",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="mapdata",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
