# Generated by Django 5.2.7 on 2025-10-15 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0039_alter_historicallayer_serialized_leaflet_json_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmapdata",
            name="campaign_link",
            field=models.CharField(
                blank=True,
                max_length=2000,
                null=True,
                validators=[django.core.validators.URLValidator(schemes=["https"])],
            ),
        ),
        migrations.AlterField(
            model_name="historicalmapdata",
            name="map_link",
            field=models.CharField(
                blank=True,
                max_length=2000,
                null=True,
                validators=[django.core.validators.URLValidator(schemes=["https"])],
            ),
        ),
        migrations.AlterField(
            model_name="mapdata",
            name="campaign_link",
            field=models.CharField(
                blank=True,
                max_length=2000,
                null=True,
                validators=[django.core.validators.URLValidator(schemes=["https"])],
            ),
        ),
        migrations.AlterField(
            model_name="mapdata",
            name="map_link",
            field=models.CharField(
                blank=True,
                max_length=2000,
                null=True,
                validators=[django.core.validators.URLValidator(schemes=["https"])],
            ),
        ),
    ]
