# Generated by Django 5.1.7 on 2025-06-20 02:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0040_alter_historicalmapdata_name_alter_mapdata_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstyle",
            name="marker_background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#F2F2F2",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AddField(
            model_name="style",
            name="marker_background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#F2F2F2",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
    ]
