# Generated by Django 5.2.7 on 2025-10-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0040_alter_historicalmapdata_campaign_link_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["display_order"]},
        ),
        migrations.AddField(
            model_name="historicalquestion",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
