# Generated by Django 5.1.7 on 2025-06-20 03:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0041_historicalstyle_marker_background_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstyle",
            name="marker_background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#F2F2F2",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Background Color",
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="marker_background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#F2F2F2",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Background Color",
            ),
        ),
    ]
