# Generated by Django 5.2.7 on 2025-10-17 21:19

from django.db import migrations, models

import rush.models.map_data


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0041_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapdata",
            name="geotiff",
            field=models.FileField(
                blank=True,
                help_text="A GeoTIFF file to upload. It may take up to a couple minutes to upload depending on the file size.",
                null=True,
                upload_to="",
            ),
        ),
    ]
