# Generated by Django 5.1.7 on 2025-06-23 19:17

import rush.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0042_alter_historicalstyle_marker_background_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstyle",
            name="marker_icon",
            field=models.TextField(
                blank=True,
                help_text="The image that will appear at each point this style is applied to.",
                max_length=100,
                null=True,
                validators=[rush.models.validators.validate_image_or_svg],
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="marker_icon",
            field=models.FileField(
                blank=True,
                help_text="The image that will appear at each point this style is applied to.",
                null=True,
                upload_to="marker_icons/",
                validators=[rush.models.validators.validate_image_or_svg],
            ),
        ),
    ]
