# Generated by Django 5.2.7 on 2025-10-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0042_alter_mapdata_geotiff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmapdata",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalquestion",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalquestiontab",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalquestiontab",
            name="question",
        ),
        migrations.RemoveField(
            model_name="historicalstyle",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="HistoricalLayer",
        ),
        migrations.DeleteModel(
            name="HistoricalMapData",
        ),
        migrations.DeleteModel(
            name="HistoricalQuestion",
        ),
        migrations.DeleteModel(
            name="HistoricalQuestionTab",
        ),
        migrations.DeleteModel(
            name="HistoricalStyle",
        ),
    ]
