# Generated by Django 5.2.7 on 2025-10-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0043_remove_historicalmapdata_history_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="display_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
