# Generated by Django 5.2.7 on 2025-10-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0044_alter_question_display_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questiontab",
            options={"ordering": ["display_order"]},
        ),
        migrations.AddField(
            model_name="questiontab",
            name="display_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
