# Generated by Django 5.2.7 on 2025-10-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0045_alter_questiontab_options_questiontab_display_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="layeronquestion",
            options={"ordering": ["display_order"]},
        ),
        migrations.AddField(
            model_name="layeronquestion",
            name="display_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="layergroup",
            name="group_description",
            field=models.TextField(blank=True, help_text="An optional description."),
        ),
    ]
