# Generated by Django 5.2.7 on 2025-10-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0046_alter_layeronquestion_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="layergroup",
            options={"ordering": ["display_order"]},
        ),
        migrations.AddField(
            model_name="layergroup",
            name="display_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
