# Generated by Django 5.2.7 on 2025-10-21 18:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0047_alter_layergroup_options_layergroup_display_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LayerGroup",
            new_name="LayerGroupOnQuestion",
        ),
        migrations.RenameModel(
            old_name="LayerOnQuestion",
            new_name="LayerOnLayerGroup",
        ),
        migrations.RenameField(
            model_name="layeronlayergroup",
            old_name="layer_group",
            new_name="layer_group_on_question",
        ),
    ]
