# Generated by Django 5.2.7 on 2025-10-21 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0049_fix_database_state"),
    ]

    operations = [
        # The question field was already removed/renamed in the database manually
        # We only need to update Django's migration state
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="layeronlayergroup",
                    name="question",
                ),
            ],
            database_operations=[
                # Database doesn't have this field anymore - it was renamed to layer_group_on_question_id
            ],
        ),
        migrations.AlterField(
            model_name="layeronlayergroup",
            name="layer_group_on_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rush.layergrouponquestion",
            ),
        ),
    ]
