# Generated by Django 5.2.7 on 2025-10-21 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0049a_populate_layergrouponquestion_question"),
    ]

    operations = [
        # Make the question field non-null now that it's populated
        migrations.AlterField(
            model_name="layergrouponquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rush.question",
            ),
        ),
        # Remove the question field from LayerOnLayerGroup since it's now on LayerGroupOnQuestion
        migrations.RemoveField(
            model_name="layeronlayergroup",
            name="question",
        ),
        # Ensure the layer_group_on_question field is properly configured
        migrations.AlterField(
            model_name="layeronlayergroup",
            name="layer_group_on_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rush.layergrouponquestion",
            ),
        ),
    ]
