# Generated by Django 5.2.7 on 2025-10-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0051_fix_layeronlayergroup_foreign_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layergrouponquestion",
            name="group_description",
            field=models.CharField(
                blank=True,
                help_text="An optional description for the group.",
                max_length=1024,
            ),
        ),
    ]
