# Generated by Django 5.2.7 on 2025-10-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0053_reorder_sortable_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="questiontab",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
