# Generated by Django 5.2.7 on 2025-10-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0053_reorder_sortable_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="layergrouponquestion",
            name="group_type",
            field=models.CharField(
                choices=[("default", "Default"), ("all_layers", "All Layers")],
                default="default",
                max_length=255,
            ),
        ),
    ]
