# Generated by Django 5.2.7 on 2025-10-22 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0054_layergrouponquestion_group_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layeronlayergroup",
            name="layer_group_on_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="layers",
                to="rush.layergrouponquestion",
            ),
        ),
    ]
