# Generated by Django 5.2.7 on 2025-10-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0055_populate_questiontab_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questiontab",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
