# Generated by Django 5.2.7 on 2025-10-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0055_alter_layeronlayergroup_layer_group_on_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="layergrouponquestion",
            old_name="group_type",
            new_name="behaviour",
        ),
    ]
