# Generated by Django 5.2.7 on 2025-10-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0056_alter_questiontab_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questiontab",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="questiontab",
            constraint=models.UniqueConstraint(
                fields=("question", "slug"), name="unique_slug_per_question"
            ),
        ),
    ]
