# Generated by Django 5.2.7 on 2025-10-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0056_rename_group_type_layergrouponquestion_behaviour"),
        ("rush", "0057_alter_questiontab_slug_and_more"),
    ]

    operations = []
