# Generated by Django 5.2.7 on 2025-10-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0058_merge_20251022_1933"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stylesonlayer",
            options={"ordering": ["display_order"]},
        ),
        migrations.RemoveField(
            model_name="stylesonlayer",
            name="legend_order",
        ),
        migrations.AddField(
            model_name="stylesonlayer",
            name="display_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
