# Generated by Django 5.2.7 on 2025-10-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0059_alter_stylesonlayer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_image_compressed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="style",
            name="is_marker_icon_compressed",
            field=models.BooleanField(default=False),
        ),
    ]
