# Generated by Django 5.2.7 on 2025-10-28 19:25

from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from rush.models import MimeType


def populate_svg_png_tiff_jpeg(apps, schema_editor):
    MimeTypeModel: MimeType = apps.get_model("rush", "MimeType")
    MimeTypeModel.objects.create(human_name="SVG", _values="image/svg+xml")
    MimeTypeModel.objects.create(human_name="PNG", _values="image/png")
    MimeTypeModel.objects.create(human_name="JPEG", _values="image/jpeg")
    MimeTypeModel.objects.create(human_name="TIFF", _values="image/tiff,image/tiff-fx")
    MimeTypeModel.objects.create(human_name="UNKNOWN", _values="")


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0059_alter_stylesonlayer_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MimeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("human_name", models.CharField(max_length=255)),
                ("_values", models.CharField(max_length=255)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("_values",), name="unique_mimetype_value")],
            },
        ),
        migrations.RunPython(code=populate_svg_png_tiff_jpeg, reverse_code=migrations.RunPython.noop),
    ]
