# Generated by Django 5.2.7 on 2025-10-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0060_question_is_image_compressed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="question_images/",
            ),
        ),
    ]
