# Generated by Django 5.2.7 on 2025-10-29 22:16
from typing import TYPE_CHECKING

from django.db import migrations
from django.db.models import QuerySet

if TYPE_CHECKING:
    from rush.models import Question, Style


def compress_question_images(apps, schema_editor):
    QuestionModel: Question = apps.get_model("rush", "Question")
    questions: QuerySet[Question] = QuestionModel.objects.all()
    for question in questions:
        if not question.is_image_compressed:
            print(f"Compressing image '{question.image}'...", end="")
            question.save()
            print("Done!")


def compress_style_marker_icons(apps, schema_editor):
    StyleModel: Style = apps.get_model("rush", "Style")
    styles: QuerySet[Style] = StyleModel.objects.all()
    for style in styles:
        if not style.is_marker_icon_compressed:
            print(f"Compressing marker_icon '{style.marker_icon}'...", end="")
            style.save()
            print("Done!")


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0061_alter_question_image copy"),
    ]

    operations = [
        migrations.RunPython(
            code=compress_question_images,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=compress_style_marker_icons,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
