# Generated by Django 5.2.7 on 2025-10-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0060_mimetype"),
        ("rush", "0062_compress_existing_question_images_and_marker_icons"),
    ]

    operations = []
