# Generated by Django 5.2.7 on 2025-10-30 03:24


from typing import TYPE_CHECKING

from django.db import migrations

if TYPE_CHECKING:
    from rush.models import MimeType


def populate_webp(apps, schema_editor):
    MimeTypeModel: MimeType = apps.get_model("rush", "MimeType")
    MimeTypeModel.objects.create(human_name="WEBP", _values="image/webp")


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0063_merge_20251030_0315"),
    ]

    operations = [
        migrations.RunPython(code=populate_webp, reverse_code=migrations.RunPython.noop),
    ]
