# Generated by Django 5.2.7 on 2025-10-30 15:34

import django.db.models.deletion
import rush.models.map_data
import rush.models.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0064_populate_webp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Icon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="icons/",
                        validators=[
                            rush.models.validators.FiletypeValidator(
                                invalid_names=None,
                                valid_names=["PNG", "JPEG", "SVG", "WEBP"],
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="mimetype",
            name="unique_mimetype_value",
        ),
        migrations.AlterField(
            model_name="mapdata",
            name="geotiff",
            field=models.FileField(
                blank=True,
                help_text="A GeoTIFF file to upload. It may take up to a couple minutes to upload depending on the file size.",
                null=True,
                storage=rush.models.map_data.get_raster_storage,
                upload_to="",
                validators=[
                    rush.models.validators.FiletypeValidator(
                        invalid_names=None, valid_names=["TIFF"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="question_images/",
                validators=[
                    rush.models.validators.FiletypeValidator(
                        invalid_names=None, valid_names=["SVG", "JPEG", "PNG", "WEBP"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="marker_icon",
            field=models.FileField(
                blank=True,
                help_text="The image that will appear at each point this style is applied to. Accepts PNG, JPEG, SVG, and WEBP files.",
                null=True,
                upload_to="marker_icons/",
                validators=[
                    rush.models.validators.FiletypeValidator(
                        invalid_names=None, valid_names=["SVG", "JPEG", "PNG", "WEBP"]
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="mimetype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_valid", True)),
                fields=("_values",),
                name="unique_mimetype_value_when_valid",
            ),
        ),
        migrations.AddField(
            model_name="icon",
            name="mime_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="rush.mimetype"
            ),
        ),
    ]
