# Generated by Django 5.2.7 on 2025-10-30 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0065_icon_remove_mimetype_unique_mimetype_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questiontab",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rush.icon",
            ),
        ),
    ]
