# Generated by Django 5.2.7 on 2025-10-30 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0067_backfill_question_tab_icons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questiontab",
            name="icon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="rush.icon"
            ),
        ),
    ]
