# Generated by Django 5.2.7 on 2025-10-31 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0068_make_icon_non_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="icon",
            name="is_file_compressed",
            field=models.BooleanField(default=False),
        ),
    ]
