# Generated by Django 5.2.7 on 2025-10-31 00:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0069_icon_is_file_compressed"),
    ]

    operations = [
        migrations.AddField(
            model_name="icon",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
