# Generated by Django 5.2.7 on 2025-10-31 02:27

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0070_icon_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiativetag",
            name="background_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="initiativetag",
            name="text_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
