# Generated by Django 5.2.7 on 2025-10-31 20:19

import django.core.validators
import django.db.models.deletion
import rush.models.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0070_icon_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="S3Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("human_name", models.CharField(max_length=255)),
                ("endpoint_url", models.CharField(max_length=2048)),
                ("key_id", models.CharField(max_length=255)),
                ("key_secret", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="mapdata",
            name="geotiff",
            field=models.FileField(
                blank=True,
                help_text="A GeoTIFF file to upload. It may take up to a couple minutes to upload depending on the file size.",
                null=True,
                upload_to="tmp_geotiff_upload_spot_new_new_new",
                validators=[
                    rush.models.validators.FiletypeValidator(
                        invalid_names=None, valid_names=["TIFF"]
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="S3File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("bucket_name", models.CharField(max_length=255)),
                (
                    "upload_url",
                    models.CharField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "local_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        validators=[
                            rush.models.validators.FiletypeValidator(
                                invalid_names=None, valid_names=["TIFF"]
                            )
                        ],
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending_upload", "Pending"),
                            ("uploading", "Uploading"),
                            ("finished_uploading", "Done"),
                        ],
                        default="pending_upload",
                        max_length=255,
                    ),
                ),
                (
                    "s3_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rush.s3client"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mapdata",
            name="s3_geotiff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rush.s3file",
            ),
        ),
    ]
