# Generated by Django 5.2.7 on 2025-11-04 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0071_initiativetag_background_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layergrouponquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="layer_groups",
                to="rush.question",
            ),
        ),
    ]
