# Generated by Django 5.2.8 on 2025-11-05 19:26

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0072_alter_layergrouponquestion_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasemapSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tile_url', models.CharField(max_length=2000, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('max_zoom', models.PositiveIntegerField()),
                ('attribution', models.TextField()),
            ],
        ),
    ]
