# Generated by Django 5.2.7 on 2025-11-13 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0073_basemapsource"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionSash",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.CharField(max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="sash",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rush.questionsash",
            ),
        ),
    ]
