# Generated by Django 5.2.7 on 2025-11-13 19:10

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0074_questionsash_question_sash"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionsash",
            name="background_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="questionsash",
            name="text_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="sash",
            field=models.ForeignKey(
                blank=True,
                help_text="A decorative sash that can be added to questions for flair.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rush.questionsash",
            ),
        ),
    ]
