# Generated by Django 5.2.7 on 2025-11-13 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0075_questionsash_background_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="sash",
            field=models.ForeignKey(
                blank=True,
                help_text="A decorative sash that can be added to questions for flair.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="rush.questionsash",
            ),
        ),
    ]
