# Generated by Django 5.2.7 on 2025-11-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0076_alter_question_sash"),
    ]

    operations = [
        migrations.AddField(
            model_name="basemapsource",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="basemapsource",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="basemapsource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="only_one_basemap_source_can_be_the_default",
            ),
        ),
    ]
