# Generated by Django 5.2.7 on 2025-11-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0077_basemapsource_is_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="basemaps",
            field=models.ManyToManyField(related_name="questions", to="rush.basemapsource"),
        ),
    ]
