# Generated by Django 5.2.7 on 2025-11-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0079_create_default_basemap_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basemapsource",
            name="name",
            field=models.CharField(
                default="Default Basemap Source Name", max_length=255
            ),
            preserve_default=False,
        ),
    ]
