# Generated by Django 5.2.7 on 2025-11-13 22:15

from django.db import migrations


def backfill(apps, schema_editor):
    """
    We want all Questions in the database to point to the default Satellite Basemap
    so something can be returned in the API when nothing is configured.
    """
    Question = apps.get_model("rush", "Question")
    BasemapSource = apps.get_model("rush", "BasemapSource")
    default_basemap = BasemapSource.objects.get(is_default=True)
    for question in Question.objects.all():
        print("Backfilling question {} with default basemap source...".format(question.title), end="")
        question.basemaps.add(default_basemap)
        print("Done!")


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0080_alter_basemapsource_name"),
    ]

    operations = [
        migrations.RunPython(
            code=backfill,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
