# Generated by Django 5.2.7 on 2025-11-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0081_backfill_default_basemap_source_to_all_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="basemaps",
            field=models.ManyToManyField(
                help_text='A basemap where the map background comes from, it specifies the "look and feel" of the map for this question. A single question can have any number of basemaps, and visitors to the site will be allowed to choose between the available options.',
                related_name="questions",
                to="rush.basemapsource",
            ),
        ),
    ]
