# Generated by Django 5.2.7 on 2025-11-13 23:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0082_alter_question_basemaps"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionsash",
            options={"verbose_name_plural": "Question Sashes"},
        ),
        migrations.RemoveField(
            model_name="question",
            name="basemaps",
        ),
        migrations.CreateModel(
            name="BasemapSourceOnQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("is_default_for_question", models.BooleanField(default=False)),
                (
                    "basemap_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rush.basemapsource",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rush.question"
                    ),
                ),
            ],
        ),
    ]
