# Generated by Django 5.2.7 on 2025-11-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0083_alter_questionsash_options_remove_question_basemaps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="basemaps",
            field=models.ManyToManyField(
                help_text='A basemap where the map background comes from, it specifies the "look and feel" of the map for this question. A single question can have any number of basemaps, and visitors to the site will be allowed to choose between the available options.',
                related_name="questions",
                through="rush.BasemapSourceOnQuestion",
                to="rush.basemapsource",
            ),
        ),
    ]
