# Generated by Django 5.2.7 on 2025-11-13 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0084_question_basemaps"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basemapsourceonquestion",
            options={"verbose_name": "Basemap"},
        ),
    ]
