# Generated by Django 5.2.7 on 2025-11-14 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0085_alter_basemapsourceonquestion_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basemapsourceonquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basemap_sources_on_question",
                to="rush.question",
            ),
        ),
    ]
