# Generated by Django 5.2.7 on 2025-11-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0086_alter_basemapsourceonquestion_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basemapsourceonquestion",
            options={"ordering": ["display_order"], "verbose_name": "Basemap"},
        ),
        migrations.AddField(
            model_name="basemapsourceonquestion",
            name="display_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
