# Generated by Django 5.2.7 on 2025-11-14 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0087_alter_basemapsourceonquestion_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="basemaps",
        ),
    ]
