# Generated by Django 5.2.7 on 2025-11-14 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0089_question_basemaps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="basemaps",
        ),
    ]
