# Generated by Django 5.2.7 on 2025-11-14 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0090_remove_question_basemaps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basemapsourceonquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basemaps",
                to="rush.question",
            ),
        ),
    ]
