# Generated by Django 5.2.7 on 2025-11-14 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0091_alter_basemapsourceonquestion_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basemapsourceonquestion",
            options={"verbose_name": "Basemap"},
        ),
        migrations.RemoveField(
            model_name="basemapsourceonquestion",
            name="display_order",
        ),
    ]
