# Generated by Django 5.2.7 on 2025-11-14 00:56

from django.db import migrations


def backfill(apps, schema_editor):
    """
    We want all Questions in the database to point to the default Satellite Basemap
    so something can be returned in the API when nothing is configured.

    This is for inlines!
    """
    Question = apps.get_model("rush", "Question")
    BasemapSource = apps.get_model("rush", "BasemapSource")
    default_basemap = BasemapSource.objects.get(is_default=True)
    BaseMapSourceOnQuestion = apps.get_model("rush", "BasemapSourceOnQuestion")
    for question in Question.objects.all():
        print("Backfilling question {} with default basemap source...".format(question.title), end="")
        BaseMapSourceOnQuestion.objects.create(
            question=question,
            basemap_source=default_basemap,
            is_default_for_question=True,
        )
        print("Done!")


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0092_alter_basemapsourceonquestion_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=backfill,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
