# Generated by Django 5.2.7 on 2025-11-15 00:10

import django.core.validators
import rush.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0093_backfill_basemap_source_inline_on_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapdata",
            name="campaign_link",
            field=models.CharField(
                blank=True,
                max_length=2000,
                null=True,
                validators=[
                    django.core.validators.URLValidator(schemes=["https"]),
                    rush.models.validators.validate_ogm_campaign_link,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mapdata",
            name="map_link",
            field=models.CharField(
                blank=True,
                max_length=2000,
                null=True,
                validators=[
                    django.core.validators.URLValidator(schemes=["https"]),
                    rush.models.validators.validate_ogm_map_link,
                ],
            ),
        ),
    ]
