# Generated by Django 5.2.7 on 2025-12-16 17:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0094_alter_mapdata_campaign_link_alter_mapdata_map_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="style",
            name="marker_background_opacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=Decimal("1"),
                max_digits=5,
                null=True,
            ),
        ),
    ]
