# Generated by Django 5.2.7 on 2025-12-16 22:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0095_style_marker_background_opacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="style",
            name="fill_opacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=Decimal(
                    "0.8000000000000000444089209850062616169452667236328125"
                ),
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="marker_background_opacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=Decimal(
                    "0.8000000000000000444089209850062616169452667236328125"
                ),
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="marker_icon_opacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=Decimal(
                    "0.8000000000000000444089209850062616169452667236328125"
                ),
                max_digits=5,
                null=True,
            ),
        ),
    ]
