# Generated by Django 5.2.9 on 2026-01-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0095_layer_legendtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='legendTitle',
            field=models.CharField(blank=True, help_text='A title what the legend description represents on the map.', null=True, verbose_name='Legend Title'),
        ),
    ]
