# Generated by Django 5.2.7 on 2025-12-17 19:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0096_alter_style_fill_opacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="style",
            name="marker_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=Decimal("22"),
                max_digits=5,
                null=True,
            ),
        ),
    ]
