# Generated by Django 5.2.7 on 2025-12-17 20:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0097_style_marker_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="style",
            name="marker_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=Decimal("22"),
                max_digits=6,
                null=True,
            ),
        ),
    ]
