# Generated by Django 5.2.7 on 2025-12-19 21:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0098_alter_style_marker_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tooltip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.TextField()),
                (
                    "offset_x",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "offset_y",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "opacity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal(
                            "0.8000000000000000444089209850062616169452667236328125"
                        ),
                        max_digits=5,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("right", "Right"),
                            ("left", "Left"),
                            ("top", "Top"),
                            ("bottom", "Bottom"),
                            ("center", "Center"),
                            ("auto", "Auto"),
                        ],
                        help_text="Where to draw the label relative to the marker.",
                        max_length=32,
                    ),
                ),
                (
                    "permanent",
                    models.BooleanField(
                        default=True,
                        help_text="Turn this off if you only want the label to be visible when a user hovers their mouse over the marker area.",
                    ),
                ),
                (
                    "sticky",
                    models.BooleanField(
                        default=True,
                        help_text="Whether text attaches to the cursor when nearby.",
                    ),
                ),
                (
                    "style_on_layer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tooltip",
                        to="rush.stylesonlayer",
                    ),
                ),
            ],
        ),
    ]
