# Generated by Django 5.2.7 on 2026-01-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0098_alter_style_marker_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layergrouponquestion",
            name="group_description",
            field=models.TextField(
                blank=True, help_text="An optional description for the group."
            ),
        ),
    ]
