# Generated by Django 5.2.9 on 2026-01-21 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0096_alter_layer_legendtitle'),
        ('rush', '0099_alter_layergrouponquestion_group_description'),
    ]

    operations = [
    ]
