# Generated by Django 5.2.7 on 2025-12-19 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0099_tooltip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tooltip",
            name="style_on_layer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tooltip",
                to="rush.stylesonlayer",
            ),
        ),
    ]
