# Generated by Django 5.2.9 on 2026-01-18 03:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0099_alter_layergrouponquestion_group_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Region name (e.g., 'Downtown', 'West Side', 'Coastal Area')", max_length=255, unique=True)),
                ('latitude', models.FloatField(help_text='Latitude coordinate for default map center')),
                ('longitude', models.FloatField(help_text='Longitude coordinate for default map center')),
                ('default_zoom', models.FloatField(default=12.0, help_text='Default zoom level for map view (e.g., 12.0 for city level)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='Regions where this question appears', related_name='questions_in_region', to='rush.region'),
        ),
    ]
