# Generated by Django 5.2.9 on 2026-01-21 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0100_region_question_regions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterField(
            model_name='region',
            name='default_zoom',
            field=models.FloatField(help_text='Default zoom level for map view (e.g., 12.0 for city level)'),
        ),
        migrations.AlterField(
            model_name='region',
            name='latitude',
            field=models.FloatField(help_text='Latitude coordinate for default map center', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.FloatField(help_text='Longitude coordinate for default map center', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(help_text="Region name (e.g., 'Downtown', 'Victoria', 'Vancouver')", max_length=255, unique=True),
        ),
    ]
