# Generated by Django 5.2.7 on 2026-01-08 22:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0100_alter_tooltip_style_on_layer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tooltip",
            name="direction",
            field=models.CharField(
                choices=[
                    ("right", "Right"),
                    ("left", "Left"),
                    ("top", "Top"),
                    ("bottom", "Bottom"),
                    ("center", "Center"),
                    ("auto", "Auto"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="tooltip",
            name="offset_x",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0"), max_digits=6
            ),
        ),
        migrations.AlterField(
            model_name="tooltip",
            name="offset_y",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0"), max_digits=6
            ),
        ),
        migrations.AlterField(
            model_name="tooltip",
            name="opacity",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal(
                    "0.8000000000000000444089209850062616169452667236328125"
                ),
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="tooltip",
            name="permanent",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="tooltip",
            name="sticky",
            field=models.BooleanField(default=True),
        ),
    ]
