# Generated by Django 5.2.9 on 2026-01-21 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0100_merge_20260120_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='region',
            field=models.ForeignKey(
                to='rush.region',
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
            ),
        ),
    ]
