# Generated by Django 5.2.9 on 2026-01-21 22:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0100_merge_20260120_2156'),
    ]

    operations = [
    ]
