# Generated by Django 5.2.7 on 2026-01-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0100_merge_20260120_2156"),
        ("rush", "0101_alter_tooltip_direction_alter_tooltip_offset_x_and_more"),
    ]

    operations = []
