# Generated by Django 5.2.7 on 2026-01-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0101_add_region_model"),
        ("rush", "0102_merge_20260122_1540"),
    ]

    operations = []
