# Generated by Django 5.2.7 on 2026-01-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0103_merge_0101_add_region_model_0102_merge_20260122_1540"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layer",
            name="legendTitle",
        ),
        migrations.AddField(
            model_name="layer",
            name="legend_title",
            field=models.CharField(
                blank=True,
                help_text="An optional title that gives more context about what the legend categories represent.",
                null=True,
                verbose_name="Legend Title",
            ),
        ),
    ]
