# Generated by Django 5.2.7 on 2026-01-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0104_remove_layer_legendtitle_layer_legend_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="published_state",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="published",
                max_length=255,
            ),
        ),
    ]
