# Generated by Django 5.2.7 on 2026-01-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0105_question_published_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="published_state",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")], max_length=255
            ),
        ),
    ]
