# Generated by Django 5.2.7 on 2026-01-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0108_initiative_published_state_layer_published_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initiative",
            name="published_state",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                help_text="WARNING: Changing this to 'Published' will make this Initiative appear on the website immediately.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="published_state",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                help_text="WARNING: Changing this to 'Published' will make this Layer appear on the website immediately.",
                max_length=255,
            ),
        ),
    ]
