# Generated by Django 5.2.7 on 2026-02-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0109_alter_initiative_published_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="questions",
        ),
    ]
