# Generated by Django 5.2.7 on 2026-03-20 22:48

import colorfield.fields
import rush.models.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0112_mapdata_arcgis_cache_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="style",
            name="circle_color",
            field=colorfield.fields.ColorField(
                default="#032697",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Color",
            ),
        ),
        migrations.AddField(
            model_name="style",
            name="circle_dash_array",
            field=models.CharField(
                blank=True,
                help_text="The pattern of dashes and gaps for the outline, e.g., '5 5' for 5 pixel long lines separated by 5 pixels of whiespace. Only digits and whitespace are allowed (e.g., '12 34 56')",
                max_length=32,
                null=True,
                validators=[
                    rush.models.validators.validate_only_integers_and_whitespace
                ],
            ),
        ),
        migrations.AddField(
            model_name="style",
            name="circle_dash_offset",
            field=models.CharField(
                blank=True,
                help_text="Offset where the dash pattern starts along the outline path.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="style",
            name="circle_line_cap",
            field=models.CharField(
                choices=[("butt", "Butt"), ("round", "Round"), ("square", "Square")],
                default="round",
                help_text="The shape of the end of a stroke. Options: butt, round, or square.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="style",
            name="circle_line_join",
            field=models.CharField(
                choices=[
                    ("arcs", "Arcs"),
                    ("bevel", "Bevel"),
                    ("miter", "Miter"),
                    ("miter-clip", "Miter Clip"),
                    ("round", "Round"),
                ],
                default="round",
                help_text="The shape used to join two lines. Options: arcs, bevel, miter, miter clip, or round.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="style",
            name="circle_opacity",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("1"),
                max_digits=5,
                verbose_name="Transparency",
            ),
        ),
        migrations.AddField(
            model_name="style",
            name="circle_radius",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5"),
                max_digits=10,
                verbose_name="Radius",
            ),
        ),
        migrations.AddField(
            model_name="style",
            name="circle_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1"),
                max_digits=10,
                verbose_name="Thickness",
            ),
        ),
        migrations.AddField(
            model_name="style",
            name="draw_circle",
            field=models.BooleanField(
                default=False,
                help_text="Check this box if you want to fill a polygon area with circles instead of a solid color. IMPORTANT: the circles are drawn using 'georeferenced units,' meaning that their size is determined by meters on the map, as opposed to pixels on the screen.",
            ),
        ),
    ]
