# Generated by Django 5.2.7 on 2026-03-20 23:21

import colorfield.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0113_style_circle_color_style_circle_dash_array_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="style",
            name="circle_fill_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#1D800C",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AddField(
            model_name="style",
            name="circle_fill_opacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=Decimal(
                    "0.8000000000000000444089209850062616169452667236328125"
                ),
                max_digits=5,
                null=True,
            ),
        ),
    ]
