# Generated by Django 5.2.7 on 2026-03-20 23:24

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0114_style_circle_fill_color_style_circle_fill_opacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="style",
            name="circle_fill_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#FFFFFF",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
    ]
