# Generated by Django 5.2.7 on 2026-03-20 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0115_alter_style_circle_fill_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="style",
            old_name="circle_color",
            new_name="circle_stroke_color",
        ),
        migrations.RenameField(
            model_name="style",
            old_name="circle_dash_array",
            new_name="circle_stroke_dash_array",
        ),
        migrations.RenameField(
            model_name="style",
            old_name="circle_dash_offset",
            new_name="circle_stroke_dash_offset",
        ),
        migrations.RenameField(
            model_name="style",
            old_name="circle_line_cap",
            new_name="circle_stroke_line_cap",
        ),
        migrations.RenameField(
            model_name="style",
            old_name="circle_line_join",
            new_name="circle_stroke_line_join",
        ),
        migrations.RenameField(
            model_name="style",
            old_name="circle_opacity",
            new_name="circle_stroke_opacity",
        ),
        migrations.RenameField(
            model_name="style",
            old_name="circle_weight",
            new_name="circle_stroke_weight",
        ),
    ]
