# Generated by Django 5.2.7 on 2026-03-25 19:40

import colorfield.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0116_rename_circle_color_style_circle_stroke_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="style",
            name="circle_radius",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("5"),
                max_digits=10,
                null=True,
                verbose_name="Radius",
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="circle_stroke_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#032697",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Stroke color",
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="circle_stroke_line_cap",
            field=models.CharField(
                blank=True,
                choices=[("butt", "Butt"), ("round", "Round"), ("square", "Square")],
                default="round",
                help_text="The shape of the end of a stroke. Options: butt, round, or square.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="circle_stroke_line_join",
            field=models.CharField(
                blank=True,
                choices=[
                    ("arcs", "Arcs"),
                    ("bevel", "Bevel"),
                    ("miter", "Miter"),
                    ("miter-clip", "Miter Clip"),
                    ("round", "Round"),
                ],
                default="round",
                help_text="The shape used to join two lines. Options: arcs, bevel, miter, miter clip, or round.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="circle_stroke_opacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=Decimal("1"),
                max_digits=5,
                null=True,
                verbose_name="Stroke transparency",
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="circle_stroke_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("1"),
                max_digits=10,
                null=True,
                verbose_name="Stroke thickness",
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="stroke_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#FFFFFF",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="stroke_line_cap",
            field=models.CharField(
                blank=True,
                choices=[("butt", "Butt"), ("round", "Round"), ("square", "Square")],
                default="round",
                help_text="The shape of the end of a stroke. Options: butt, round, or square.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="stroke_line_join",
            field=models.CharField(
                blank=True,
                choices=[
                    ("arcs", "Arcs"),
                    ("bevel", "Bevel"),
                    ("miter", "Miter"),
                    ("miter-clip", "Miter Clip"),
                    ("round", "Round"),
                ],
                default="round",
                help_text="The shape used to join two lines. Options: arcs, bevel, miter, miter clip, or round.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="stroke_opacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=Decimal("1"),
                max_digits=5,
                null=True,
                verbose_name="Transparency",
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="stroke_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("1"),
                max_digits=10,
                null=True,
                verbose_name="Thickness",
            ),
        ),
    ]
