# Generated by Django 5.2.7 on 2026-04-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0117_alter_style_circle_radius_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basemapsource",
            name="attribution_strict_clean",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="initiative",
            name="content_strict_clean",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="layer",
            name="description_strict_clean",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="layergrouponquestion",
            name="group_description_strict_clean",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="page",
            name="content_strict_clean",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="questiontab",
            name="content_strict_clean",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="stylesonlayer",
            name="legend_description_strict_clean",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tooltip",
            name="label_strict_clean",
            field=models.BooleanField(default=True),
        ),
    ]
