# Generated by Django 5.2.7 on 2026-04-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0118_basemapsource_attribution_strict_clean_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stylesonlayer",
            name="popup_strict_clean",
            field=models.BooleanField(default=True),
        ),
    ]
