# Generated by Django 5.2.7 on 2026-04-23 01:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0121_clean_initiative_content_again"),
    ]

    operations = [
        migrations.CreateModel(
            name="Geometry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("data", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                (
                    "mapdata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rush.mapdata"
                    ),
                ),
            ],
        ),
    ]
