# Generated by Django 5.2.7 on 2026-04-23 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0122_geometry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="geometry",
            old_name="mapdata",
            new_name="map_data",
        ),
    ]
