# Generated by Django 5.2.7 on 2026-04-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0123_rename_mapdata_geometry_map_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="geometry",
            name="properties",
            field=models.JSONField(default={}),
        ),
    ]
