# Generated by Django 5.2.11 on 2026-04-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0124_geometry_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometry',
            name='properties',
            field=models.JSONField(default=dict),
        ),
    ]
