# Generated by Django 5.2.7 on 2026-10-01 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0125_remove_channel_is_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="questiontab",
            name="center_lat",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="questiontab",
            name="center_long",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="questiontab",
            name="zoom",
            field=models.IntegerField(
                blank=True,
                help_text="automatically zooms the map when a question tab is clicked. defaults to None, which means that the map will stay at its current zoom level.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(23),
                ],
            ),
        ),
    ]
