# Generated by Django 5.2.7 on 2026-10-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0126_questiontab_center_lat_questiontab_center_long_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questiontab",
            name="center_lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="questiontab",
            name="center_long",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
