# Generated by Django 5.2.7 on 2026-10-01 23:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rush", "0127_questiontab_center_precision"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayerOnQuestionTab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rush.layer"
                    ),
                ),
                (
                    "question_tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rush.questiontab",
                    ),
                ),
            ],
            options={
                "verbose_name": "Layer on question tab",
            },
        ),
        migrations.AddField(
            model_name="questiontab",
            name="layers",
            field=models.ManyToManyField(
                blank=True,
                help_text="layers to toggle on when a question tab is clicked. they don't need to be on the question.",
                related_name="question_tabs",
                through="rush.LayerOnQuestionTab",
                to="rush.layer",
            ),
        ),
        migrations.AddConstraint(
            model_name="layeronquestiontab",
            constraint=models.UniqueConstraint(
                fields=("question_tab", "layer"), name="unique_layer_per_question_tab"
            ),
        ),
    ]
