name: Deploy prod when push to main

on:
  push:
    branches:
      - main

jobs:
  send_webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send Deploy Webhook to RUSH Admin Site
        env:
          WEBHOOK_URL: "https://whatstherush.earth/github/deploy/"
          SECRET: ${{ secrets.DEPLOY_WEBHOOK_SECRET }}
        run: |
          PAYLOAD='{"repository": "${{ github.repository }}", "ref": "${{ github.ref }}", "action": "deploy-prod"}'

          SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$SECRET" | awk '{print $2}')

          curl -X POST "$WEBHOOK_URL" \
               -H "Content-Type: application/json" \
               -H "X-Hub-Signature-256: sha256=$SIGNATURE" \
               -d "$PAYLOAD"
